version: "3"

services:
  api:
    build:
      context: ./src/Echo
      dockerfile: Dockerfile
    environment:
      - DB=${API_DBCONNSTRING}
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: on-failure:3

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    ports:
      - 5432:5432
